public class RRAPromptTemplates {
  public static final String ENTITIES_DATACLOUD_SEARCH = 'RRA_EntitiesDatacloudSearch';
  public static final String ENTITY_MATCHER = 'RRA_EntityMatcher';
  public static final String APPEND_RELATIONSHIPS = 'RRA_AppendRelationships';
  public static final String ENTITIES_FROM_CRM = 'RRA_EntitiesFromCRM';
  public static final String CONSOLIDATE_INSIGHTS = 'RRA_ConsolidateInsights';
  public static final String CONSOLIDATE_CROSS_SOURCE_INSIGHTS = 'RRA_ConsolidateCrossSourceInsights';
  public static final String COMMON_NAME_VARIANTS = 'RRA_CommonNameVariants';
  public static final String DEEP_WEB_RESEARCH_DISCOVERY = 'RRA_DeepWebResearch_Discovery';
  public static final String DEEP_WEB_RESEARCH_REFINEMENT = 'RRA_DeepWebResearch_Refinement';
}
